add -o option to save to file

diff --git a/wifi2qr b/wifi2qr
--- a/wifi2qr
+++ b/wifi2qr
@@ -11,12 +11,14 @@ show_list=false
 show_help=false
 quiet=false
 mode=UTF8
-while getopts lhaiq optval; do
+fn=
+while getopts lhaiqo: optval; do
     case $optval in
         l) show_list=true ;;
         h) show_help=true ;;
         a) mode=ANSI ;;
-        i) mode=PNG; if ! which display >/dev/null; then echo "ERROR: display not found in path" >&2; exit 1; fi ;;
+        o) fn="$OPTARG"; ext=$(sed 's|^.*\.\(.*\)|\U\1|' <<< "$fn"); mode=${ext:-PNG} ;;
+        i) mode=DISPLAY; if ! which display >/dev/null; then echo "ERROR: display not found in path" >&2; exit 1; fi ;;
         q) quiet=true ;;
         \?) show_help=true ;;
     esac
@@ -40,7 +42,7 @@ if [[ $show_list != true && $show_help != true ]]; then
 fi
 
 if [[ $show_help == true ]]; then
-    echo "$(basename $0) [-h] [-l] [-u | -a] [connection]" >&2
+    echo "$(basename $0) [-h] [-l] [-a | -i | -o FILE] [connection]" >&2
     echo >&2
     echo "Displays a QR code that can be scanned to connect to a WiFi network" >&2
     echo "known to NetworkManager." >&2
@@ -51,6 +53,7 @@ if [[ $show_help == true ]]; then
     echo "  -h            Show this help message" >&2
     echo "  -l            List WiFi connections known to NetworkManager" >&2
     echo "  -a | -i       Show QR code using ANSI characters or with ImageMagick" >&2
+    echo "     | -o FILE  or save to a file (e.g. qrcode.png)" >&2
     echo "                (default is to show using UTF8 characters)" >&2
     echo "  -q            Quiet mode (default is to print barcode in text" >&2
     echo "                form to stderr as well; this suppresses it)" >&2
@@ -90,11 +93,13 @@ done
 [[ -z "$ssid" ]] && echo "ERROR: could not parse nmcli output" >&2 && exit 1
 
 barcode="WIFI:S:${ssid}${pass}${hidden};"
-if [[ $mode != PNG ]]; then
+if [[ $mode == ANSI || $mode == UTF8 ]]; then
     qrencode -t "$mode" -o- "$barcode"
-else
-    qrencode -o- "$barcode" |
+elif [[ $mode == DISPLAY ]]; then
+    qrencode -t PNG -o- "$barcode" |
         display -geometry -0-0 -sample 300% -title "Share WiFi: $ssid" - &
+else
+    qrencode -t "$mode" -o "$fn" "$barcode"
 fi
 if [[ $quiet != true ]]; then
     echo "$barcode" >&2
